name: stroktrail
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  infinite_scroll_pagination: ^3.1.0
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flash: ^2.0.3+2
  flutter_smart_dialog: ^3.4.2+2
  lottie: ^1.3.0
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  cupertino_icons: ^1.0.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
